<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.github.tobiasmiosczka</groupId>
        <artifactId>builder-gen</artifactId>
        <version>main-SNAPSHOT</version>
    </parent>

    <artifactId>builder-gen-core</artifactId>
    <packaging>jar</packaging>

    <name>builder-gen : builder-gen-core</name>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.github.tobiasmiosczka</groupId>
                <artifactId>builder-gen</artifactId>
                <version>${project.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>com.github.javaparser</groupId>
            <artifactId>javaparser-core</artifactId>
        </dependency>
        <dependency>
            <groupId>com.github.javaparser</groupId>
            <artifactId>javaparser-symbol-solver-core</artifactId>
        </dependency>
    </dependencies>
</project>